name: Project Deployed

on:
  push:
    branches:
      - main

jobs:
  run-linters:
    name: Run deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run build
        run: npm run build
