name: Push to Main

on:
  push:
    branches: 'Dev'
  workflow_dispatch: # Allows you to run this workflow manually from the GitHub Actions tab

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Dev branch
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Merge Dev into Main
        run: |
          git merge Dev --allow-unrelated-histories

      - name: Commit the merge
        if: github.event_name == 'push'
        run: |
          git commit -m "Merge dev into main" || echo "No changes to commit"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # Use the personal access token
        run: |
          git push origin main
