name: Main tasks

on:
  push:
    branches: 'main'

jobs:
  job1:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run prettier
        run: npm run prettier

      - name: Run linters
        run: npm run lint

  job2:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
