name: Push to main

on:
  workflow_run:
    workflows: ['Lint and Prettier configurations', 'Testing App'] # The workflows that must complete first
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Dev branch
        uses: actions/checkout@v2
        with:
          ref: Dev

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge Dev into Main
        run: |
          git checkout main
          git merge Dev --no-ff -m "Deploy: merge Dev into Main"

      - name: Push to Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
